-- Sprint 2 seed data (idempotent)

INSERT INTO organizations (id, name)
VALUES ('00000000-0000-0000-0000-000000000001', 'Revendis Demo')
ON CONFLICT (id) DO NOTHING;

INSERT INTO stores (id, organization_id, name, timezone)
VALUES ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000001', 'Loja Centro', 'America/Sao_Paulo')
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, organization_id, email, name, role)
VALUES ('00000000-0000-0000-0000-000000000201', '00000000-0000-0000-0000-000000000001', 'owner@revendis.local', 'Owner Demo', 'owner')
ON CONFLICT (id) DO NOTHING;

INSERT INTO products (id, organization_id, sku, name, barcode, price, cost)
VALUES ('00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000001', 'SKU-001', 'Produto Demo', '7890000000000', 49.90, 29.90)
ON CONFLICT (id) DO NOTHING;

INSERT INTO inventory_balances (id, store_id, product_id, quantity)
VALUES ('00000000-0000-0000-0000-000000000401', '00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000301', 50)
ON CONFLICT (store_id, product_id)
DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now();

INSERT INTO customers (id, organization_id, name, phone, email)
VALUES ('00000000-0000-0000-0000-000000000501', '00000000-0000-0000-0000-000000000001', 'Cliente Demo', '+5511999999999', 'cliente@revendis.local')
ON CONFLICT (id) DO NOTHING;

INSERT INTO sales (id, store_id, customer_id, status, subtotal, discount_total, total)
VALUES ('00000000-0000-0000-0000-000000000601', '00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000501', 'confirmed', 99.80, 0, 99.80)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sale_items (id, sale_id, product_id, sku, quantity, price)
VALUES ('00000000-0000-0000-0000-000000000701', '00000000-0000-0000-0000-000000000601', '00000000-0000-0000-0000-000000000301', 'SKU-001', 2, 49.90)
ON CONFLICT (id) DO NOTHING;

INSERT INTO payments (id, sale_id, method, amount)
VALUES ('00000000-0000-0000-0000-000000000801', '00000000-0000-0000-0000-000000000601', 'pix', 99.80)
ON CONFLICT (id) DO NOTHING;

INSERT INTO receivables (id, sale_id, amount, due_date, status)
VALUES ('00000000-0000-0000-0000-000000000901', '00000000-0000-0000-0000-000000000601', 99.80, '2026-02-01', 'pending')
ON CONFLICT (id) DO NOTHING;

-- Inventory movements are generated by real operations; keep seed balances stable.
